// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace MahmoudIbrahim_sun_wed_5pm_C__EF_03.Models
{
    public partial class CustOrderHistResult
    {
        public string ProductName { get; set; } = default!;
        public int? Total { get; set; }
    }
}
