// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace MahmoudIbrahim_sun_wed_5pm_C__EF_03.Models
{
    public partial class EmployeeSalesbyCountryResult
    {
        public string? Country { get; set; }
        public string LastName { get; set; } = default!;
        public string FirstName { get; set; } = default!;
        public DateTime? ShippedDate { get; set; }
        public int OrderID { get; set; }
        public decimal? SaleAmount { get; set; }
    }
}
