// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using MahmoudIbrahim_sun_wed_5pm_C__EF_03.Models;

namespace MahmoudIbrahim_sun_wed_5pm_C__EF_03.Models
{
    public partial class NorthwindContext
    {

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
