// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace MahmoudIbrahim_sun_wed_5pm_C__EF_03.Models
{
    public partial class SelectAllCategoriesResult
    {
        public int CategoryID { get; set; }
        public string CategoryName { get; set; } = default!;
        public string? Description { get; set; }
    }
}
